// Generated by CoffeeScript 1.6.3
(function() {
  App.lang.strings.lg = {
    'head': 'Zūlis turnirs',
    'Help': 'Pavyiceiba',
    'Tournament data': 'Turnira dati',
    'Timer': 'Taimers',
    'About application': 'Par aplikaceji',
    'Sure?': 'Puorlīcynuots?',
    'Name/surname': 'Vuords/pavuords',
    'Total': 'Kūpā',
    'New player': 'Īvodi spieļietoju i spīd < Enter >',
    'New round': 'Vēļ kuorta',
    'Reorder': 'Sakuortot piec punktim',
    'Remove one': 'Izsveitruot vīnu švakuokū kuortu',
    'Give new number': 'Īdūt kotram jaunu numuru?',
    'New round confirm?': 'Vēl vīna kuorta?',
    'Start': 'Suokt',
    'Reset timer?': 'Nūmest taimeri?',
    'Timer instructions': "<p>Īvodit minutis (ka atsaškir nu 45), i spīd \"Suokt\".</p>\n<p>\"Pauze\", ka vāg uzpauzēt, ūtrū raizi daspīd, kod joturpynoj.</p>",
    'Tournament data instruction': "<p></p>\n",
    'Index tutorial': "<h1>Zūlis turnira <small>Aplikaceja</small></h1>",
    'About': "<h1>Zūlis turniru <small>Aplikaceja</small></h1>\n<p>\n  Atvīgloi turnira organiziešonu:\n</p>\n<ul>\n  <li>Punktu skaitiešonu</li>\n  <li>Spieļotoju davīnošonu</li>\n  <li>Laika skaitiešonu</li>\n  <li>Laika paziņošonu</li>\n  <li>Spieļotoju šķirošonu piec punktim</li>\n</ul>\n<p>Drūši varat lītot piec sovim īskotim, nūrodūt apakšā atpakaļsaiti uz autorim!</p>"
  };

}).call(this);
