// Generated by CoffeeScript 1.6.3
(function() {
  App.lang.strings.lv = {
    'head': 'Zoles turnīrs',
    'Help': 'Pamācība',
    'Tournament data': 'Turnīra dati',
    'Timer': 'Taimeris',
    'About application': 'Par aplikāciju',
    'Sure?': 'Vai esi pārliecināts?',
    'Name/surname': 'Vārds/uzvārds',
    'Total': 'Kopā',
    'New player': 'Ievadi vārdu un spied < Enter >',
    'New round': 'Vēl kārta',
    'Reorder': 'Sakārtot pēc punktiem',
    'Remove one': 'Izsvītrot sliktāko kārtu',
    'Give new number': 'Iedot katram jaunu dalības numuru?',
    'New round confirm?': 'Pievienot vēl vienu kārtu?',
    'Start': 'Sākt',
    'Reset timer?': 'Nomest taimeri?',
    'Timer instructions': "<p>Ievadi minūtes (ja atšķiras no 45) un spied \"Sākt\".</p>\n<p>\"Pauze\", ja nepieciešams uzpauzēt, piespied otro reizi, lai turpinātu skaitīt.</p>",
    'Tournament data instruction': "  <p>Ievadi pirmo vārdu un nospied < Enter >, tad ievadi kārtas (jeb raundus/posmus) ar pogu \"Vēl kārta\" (parasti 6).\nSavadi pārējus lietotājus.</p>\n  <p>Kad visi lietotāji savadīti, nospied \"Random\", tas piešķirs katram dalībniekam kārtas numuru izlozes secībā.\nSpied \"Sakārtot pēc punktiem\", tas sakārtos dalībniekus pēc reitinga/kārtas numura.</p>\n  <p>Kad pirmā kārta nospēlēta, savadām rezultātus tabulā, nospiežot uz -. Vadiet lielos punktus un mazos punktus iekavās\n(piemēram 6 (55), 2 (-15) utt.), lai pieglabātu jāspiež < Enter > (vai < Escape >). Kad punkti savadīti,\n  tad var pārbaudīt kontrolsummu pēdējā cilnī (apakšā). Spiežam \"Sakārtot pēc punktiem\" un sākam nākošo kārtu.</p>\n  <p>Poga \"Izsvītrot sliktāko kārtu\" izdzēsis sliktāko kārtu katram dalībniekam. Piespiediet otro reizi, lai noņemtu.</p>",
    'Index tutorial': "<h1>Zoles turnīra <small>Aplikācija</small></h1>\n<p>Programmu jālieto ar Mozilla Firefox vai Google Chrome jaunāko versiju.</p>\n<p>Jāņem vērā, ka visi ievadītie dati tiek glabāti lokāli uz jūsu datora.</p>\n<p>\n  Augšā ir četras navigācijas pogas:\n</p>\n<p>\n  1) <strong>Pamācība</strong> — šī sadaļa\n</p>\n<p>\n  2) <strong>Turnīra dati</strong> — turnīra rezultāti un tabula aprēķiniem\n</p>\n<p>\n  3) <strong>Taimeris</strong> — speciāls atpakaļskaitīšanas taimeris ar atgādināšanas skaņas signāliem (uz 15, 5, 1 un 0 min.)\n</p>\n<p>\n  4) <strong>Par aplikāciju</strong> — programmas apraksts\n</p>",
    'About': "<h1>Zoles turnīrs <small>Aplikācija</small></h1>\n<p>\n  Atvieglo turnīra organizēšanu:\n</p>\n<ul>\n  <li>Punktu skaitīšana</li>\n  <li>Spēlētāju pievienošana</li>\n  <li>Laika skaitīšana</li>\n  <li>Laika beigu paziņojumi</li>\n  <li>Spēlētāju kārtošana pēc punktiem</li>\n</ul>\n<p>Droši varat lietot pēc saviem ieskatiem, norādot apakšā atpakaļsaiti uz autoriem!</p>"
  };

}).call(this);
